server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devtalk_test_db?serverTimezone=Asia/Seoul
    username: root
    password: ${MYSQL_PASSWORD}

  # spring-boot-mail
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: dev.hongik@gmail.com # sender
    password: ${SPRING_MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # AWS S3 Configuration
  cloud:
    aws:
      region:
        static: ap-northeast-2  # Seoul region
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  token:
    secretKey: ${JWT_SECRET}
    expiration:
      access: 14400000

aws:
  s3:
    bucket: ${AWS_S3_BUCKET_NAME}
    cloudfront-domain: ${AWS_CLOUDFRONT_DOMAIN:}  # Optional CloudFront domain